### ISSUE TITLE
Trying to get it to run level00

### ISSUE THREAD

**Issue by ls-michielrensen** [stripe-ctf/stripe-ctf-2.0#4]
I firstly would like to thank the people at Stripe for releasing the source code for the levels of this CTF-challenge. I'm trying to set up a CTF for the guys in my team to hone our skills but mostly to have fun. I'm using the excellent Vagrant set up from https://github.com/e28eta/stripe-ctf-2.0. Although I'm getting somewhere, I'm kinda stuck in running level00 (haven't even tried to other levels yet). I'm getting this error

```
Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.forEach.Object.defineProperty.get (/levels/00/node_modules/express/lib/express.js:89:13)
    at Object.<anonymous> (/levels/00/level00.js:22:17)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

Which makes me think I'm running a too new version of the components used for this level. I wonder if anyone knows which version of the "express" package was used or if anyone knows how to solve this. So far I've tried installing the suggested packages manually, but no luck.

**Comment by ls-michielrensen** [comment]
The PR https://github.com/stripe-ctf/stripe-ctf-2.0/pull/3 solves the exact same issue
